version: '3'
services:
  mysql:
    restart: always
    container_name: "mysql"
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - "mysql"
    depends_on:
      - mysql
volumes:
  db_data:
