version: '3'
services:
  mysql:
    restart: always
    container_name: "oursql"
    image: mysql:latest
    ports:
      - "3002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 31f58458f0cf8691fe88ab7e7720eea9089fd9863
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: 31f58458f0cf8691fe88ab7e7720eea9089fd986
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - "mysql"
    depends_on:
      - mysql
volumes:
  db_data:
